### ISSUE TITLE
Identity Paths Don't Simplify On Left Hand Side

### ISSUE THREAD

**Issue by AHartNtkn** [mortberg/cubicaltt#11]
When composing identity paths to the right of some other path p, the composition simplifies to p;

```
IdPathTest1 (A : U) (a b : A) (p : Id A a b) : Id (Id A a b) p (<i> comp A (p @ i) [(i=1) -> <_> b]) = <_> p
IdPathTest2 (A : U) (a b : A) (p : Id A a b) : Id (Id A a b) p (<i> comp A (p @ i) [(i=1) -> <_> b]) = <_ i> comp A (p @ i) [(i=1) -> <_> b]
IdPathTest3 (A : U) (a b : A) (p : Id A a b) : Id (Id A a b) p (<i> comp A (p @ i) [(i=1) -> <_> b]) = <_ i> comp A (p @ i) [(i=0) -> <_> a]

IdPathTest4 (A : U) (a b : A) (p : Id A a b) : Id (Id A a b) p (<i> comp A (p @ i) [(i=0) -> <_> a]) = <_> p
IdPathTest5 (A : U) (a b : A) (p : Id A a b) : Id (Id A a b) p (<i> comp A (p @ i) [(i=0) -> <_> a]) = <_ i> comp A (p @ i) [(i=0) -> <_> a]
IdPathTest6 (A : U) (a b : A) (p : Id A a b) : Id (Id A a b) p (<i> comp A (p @ i) [(i=0) -> <_> a]) = <_ i> comp A (p @ i) [(i=1) -> <_> b]
```

However, this doesn't happen when composing an identity path on the left side of p.

```
--Tests 7, 8, and 10 fail
--IdPathTest7 (A : U) (a b : A) (p : Id A a b) : Id (Id A a b) p (<i> comp A a [(i=1) -> <k> p @ k]) = <_> p
--IdPathTest8 (A : U) (a b : A) (p : Id A a b) : Id (Id A a b) p (<i> comp A b [(i=0) -> <k> p @ -k]) = <_> p
IdPathTest9 (A : U) (a b : A) (p : Id A a b) : Id (Id A a b) p p = <_ i> comp A (p @ i) [(i=0) -> <_> a]
--IdPathTest10 (A : U) (a b : A) (p : Id A a b) : Id (Id A a b) p p = <_ i> comp A a [(i=1) -> <k> p @ k]
```

Is this behavior correct? If so, why does this happen?

**Comment by coquand** [comment]
The operation of composition in a type A takes a cube in A and intuitively replace
some faces of this cube along a compatible system of equalities. 

 An equality between two cubes a0 and a1 can be seen as a path a0 -> a1
in some direction i. It is constant if it does not depend on i.

 The only judgement law for this operation (which is justified by induction on the type)
is that this operation is the identity operation if all these equalities are constant.

 In particular

 comp A (p@i) [(i=1) -> q]              is p@i   if q is constant

but we cannot say anything about

 comp A a [(i=1) -> q]

if a does not depend on i.
 Actually, it may not be so clear even to state what the general law should be.

(There is something similar in MLTT; when defining composition by Id-elimination, composition
simplifies only on one side.)

 This law can be refined by the fact that we can remove or add any constant equality
without changing the result of the composition.

 We have a similar law for the transport operation which takes a path in the universe
and produce a function between the two endpoints of this path: this function is the identity
function if the path is constant.

**Comment by AHartNtkn** [comment]
I kind of understand what you mean when you mention simplifying/evaluating on one side only.

You mentioned a similar law for transport, so I tried these tests using transport to see what would happen. I used a path from nat to list Unit to experiment with. Here is that code, for the sake of completeness;

```
data nat = zero | suc (n : nat)
data list (A : U) = nil | cons (a : A) (as : list A)
data Unit = tt

nat2LU : nat -> list Unit = split
  zero  -> nil
  suc n -> cons tt (nat2LU n)

LU2nat : list Unit -> nat = split
  nil       -> zero
  cons tt l -> suc (LU2nat l)

natLUiso : (n : nat) -> Id nat (LU2nat (nat2LU n)) n = split
  zero  -> <i> zero
  suc n -> <i> suc (natLUiso n @ i)

being : (a : Unit) -> Id Unit a tt = split
  tt -> <i> tt

LUnatiso : (l : list Unit) -> Id (list Unit) (nat2LU (LU2nat l)) l = split
  nil  -> <i> nil
  cons a l -> <i> cons (being a @ -i) (LUnatiso l @ i)

natLUId : Id U nat (list Unit) =
  <i> glue (list Unit) [ (i = 0) -> (nat,nat2LU,LU2nat,LUnatiso,natLUiso) ]
```

I started by constructing the four ways of composing an identity to natLUId;

```
natLUc1 : Id U nat (list Unit) = <i> comp U (natLUId @ i) [ (i = 1) -> <_> list Unit ]
natLUc2 : Id U nat (list Unit) = <i> comp U (natLUId @ i) [ (i = 0) -> <_> nat ]
natLUc3 : Id U nat (list Unit) = <i> comp U nat [ (i = 1) -> <k> natLUId @ k ]
natLUc4 : Id U nat (list Unit) = <i> comp U (list Unit) [ (i = 0) -> <k> natLUId @ -k ]
```

I then used transport to turn them all into functions;

```
natLUf0 (n : nat) : list Unit = transport natLUId n
natLUf1 (n : nat) : list Unit = transport natLUc1 n
natLUf2 (n : nat) : list Unit = transport natLUc2 n
natLUf3 (n : nat) : list Unit = transport natLUc3 n
natLUf4 (n : nat) : list Unit = transport natLUc4 n
```

I then tried to prove that these were all the same function;

```
tranTest1 : Id (nat -> list Unit) natLUf0 natLUf1 = <i> natLUf0
tranTest2 : Id (nat -> list Unit) natLUf0 natLUf2 = <i> natLUf0
tranTest3 : Id (nat -> list Unit) natLUf0 natLUf3 = <i> natLUf0
tranTest4 : Id (nat -> list Unit) natLUf0 natLUf4 = <i> natLUf0
```

And this works perfectly. All the tests pass. Whatever difference between &lt;i> comp U nat [ (i = 1) -> <k> natLUId @ k ] and natLUId that comp cares about gets erased by transport.

Is this really just some technical detail about how comp works? Is there some preferred way around it? For reference, this was one of the things I was trying to construct when I ran into this;

```
CommSquar2 (A : U) (a00 a10 a01 a11 : A) (a0010 : Id A a00 a10) (a0001 : Id A a00 a01) (a1011 : Id A a10 a11) (a0111 : Id A a01 a11)
           (Sq : Square A a00 a10 a0010
                          a01 a11 a0111 a0001 a1011) :
           Id (Id A a00 a11) (<i> comp A (a0010 @ i) [ (i=1) -> <k> a1011 @ k ])
                             (<i> comp A (a0001 @ i) [ (i=1) -> <k> a0111 @ k ]) =
           <i j> comp A (a0001 @ i /\ j) [(j=1) ->
                 <j> comp A (Sq @ j @ i) [(j=1) -> <j> a1011 @ (j \/ i) ] ]
```

That of course doesn't compile, since the path starts at 

```
(<j> comp A a00 [ (j = 1) -> <k> comp A (a0010 @ k) ...
```

instead of

```
(<k> comp A (a0010 @ k) ....
```

How could this be done?

**Comment by coquand** [comment]
> And this works perfectly. All the tests pass. Whatever difference between <i> comp U nat [ (i = 1) -> natLUId @ k ] and natLUId that comp cares about gets erased by transport.
> 
>  Yes. What happens is that 

  if    r = <i> comp U (p@i) [(i=1) -> q]   :   Id U (p @ 0) (q@1)

then

 transport r x = transport q (transport p x)  : q@1     if   x : p@ 0

and 

 -if p is constant this is the same as    transport q x
 -if q is constant this is the same  as   transport p x

 For the square example, one might start to consider the diagonal of the square   

 <i> Sq @ i @ i

and shows that this diagonal is equal to both compositions, and then conclude by composing these proofs.

   I attach such a proof (but there may be shorter proofs)

**Comment by AHartNtkn** [comment]
Thank you. Your proof doesn't seem to actually be attached, but following your advice to consider Sq @ i @ i, I came up with this proof;

```
CommSquar2 (A : U) (a00 a10 a01 a11 : A) (a0010 : Id A a00 a10) (a0001 : Id A a00 a01) (a1011 : Id A a10 a11) (a0111 : Id A a01 a11)
           (Sq : Square A a00 a10 a0010
                          a01 a11 a0111 a0001 a1011) :
           Id (Id A a00 a11) (<i> comp A (a0010 @ i) [ (i=1) -> <k> a1011 @ k ])
                             (<i> comp A (a0001 @ i) [ (i=1) -> <k> a0111 @ k ]) =
           <i j> comp A (lem1 @ i @ j) [(i=1) -> <k> lem2 @ k @ j ]
             where
             lem1 : Id (Id A a00 a11) (<i> comp A (a0010 @ i) [ (i=1) -> <k> a1011 @ k ]) (<i> Sq @ i @ i) =
               <i j> comp A (Sq @ j @ (j /\ i)) [ (j = 1) -> <j> a1011 @ (j \/ i) ]

             lem2 : Id (Id A a00 a11) (<i> Sq @ i @ i) (<i> comp A (a0001 @ i) [ (i=1) -> <k> a0111 @ k ]) =
               <i j> comp A (Sq @ (j /\ -i) @ j) [ (j = 1) -> <j> a0111 @ (j \/ -i) ]
```

Anyway, it's clear at this point that there is no glitch or incorrect behavior, but I think this was helpful anyway. Thank you for your time.
