### ISSUE TITLE
Makefile incorrect?

### ISSUE THREAD

**Issue by markfarrell** [mortberg/cubicaltt#13]
Hi, 

I was trying to build `cubicaltt`, but ran into a bit of trouble. I installed the require packages with cabal, but then ran into problems with `make bnfc && make`. Here's what I had to do instead:

``` bash
bnfc -d --haskell --ghc --alex3 Exp.cf
happy -gca Exp/Par.y
alex -g Exp/Lex.x
ghc --make -O2 Exp/Test.hs -o Exp/Test
ghc --make -O2 -o cubical -rtsopts Main.hs
```

Should the Makefile be fixed?

**Comment by mortberg** [comment]
This is strange. I think I have the latest version of all packages and I don't have any trouble:

$ bnfc --version
2.8
$ alex --version
Alex version 3.1.4, (c) 2003 Chris Dornan and Simon Marlow
$ happy --version
Happy Version 1.19.5 Copyright (c) 1993-1996 Andy Gill, Simon Marlow (c) 1997-2005 Simon Marlow
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.1

Do you have the same versions? What system are you on?
