### ISSUE TITLE
Strictness of ap (f o g) = (ap f) o (ap g)

### ISSUE THREAD

**Issue by javra** [mortberg/cubicaltt#15]
Hi,

is the above equality definitional in cubicaltt? I expected this to work:

```
testApComp (A B C : U) (f : A -> B) (g : B -> C) (a b : A) (p : Id A a b) :
           Id (Id C (g (f a)) (g (f b)))
           (mapOnPath B C g (f a) (f b) (mapOnPath A B f a b p))
           (mapOnPath A C (\(x : A) -> (g (f x))) a b p) =
           refl (Id C (g (f a)) (g (f b))) (mapOnPath A C (\(x : A) -> (g (f x))) a b p)
```

But it does not. It seems to boil down to whether terms like `comp (<!1> B) (f (p @ !0)) [ (!0 = 0) -> <!1> f a, (!0 = 1) -> <!1> f (q @ !1) ]` could get normalized to
`f (comp (<!1> A) (p @ !0) [ (!0 = 0) -> <!1> a, (!0 = 1) -> <!1> q @ !1 ]` ...

**Comment by coquand** [comment]
Hello,
 What versions are you using? The example works as you wrote it when I tried it
(and indeed it should work).

**Comment by javra** [comment]
Ah, I just misinterpreted an error message. It was the line afterwards that did not work. Thank you!
