### ISSUE TITLE
Maintain semantics of type signatures

### ISSUE THREAD

**Issue by abooij** [mortberg/cubicaltt#25]
In many proofs, instead of writing:

```
propIsProp (A : U) : prop (prop A) = ...
```

one expands definitions, and instead writes

```
propIsProp (A : U) (f g : prop A) : Id (prop A) f g = ...
```

to be able to bind variable names. This cannot be done using lambdas because their scope doesn't reach where clauses (which is often necessary).

However, clearly the former expression is the one we'd like to see in clean, readable code. 

Not sure what the best way to solving this is, though. I suppose in agda this is not a problem because the type signature is separate from the implementation, and thus variables can be bound even if their type isn't explicitly written out. So in that sense this could be related to #12?

**Comment by simhu** [comment]
If one writes the expression with lambdas, one should use a let instead of a where (where clauses are attached to declarations).  This should already work in the current version.

**Comment by mortberg** [comment]
As Simon said one can use a let instead. So you can prove propIsProp this way if you want:

```
propIsProp (A : U) : prop (prop A) =
  \(f g : prop A) -> <i> \(a b : A) ->
    let fab : Id A a b = f a b
        gab : Id A a b = g a b
    in propSet A f a b fab gab @ i
```
