### ISSUE TITLE
Composing with refl gives different path

### ISSUE THREAD

**Issue by abooij** [mortberg/cubicaltt#28]
In the context of the interval, I found the following.

```
fromUnitK' : (a : I) -> Id I (fromUnit (toUnit a)) a = split
  zero -> <i> zero
  one -> <i> seg {I} @ i
  -- the usual case here is:
  -- seg @ i -> <j> (seg {I} @ i /\ j)
  -- but try p (which works) vs. p' (which doesn't):
  seg @ i -> p'
    where
    p : Id I zero (seg {I} @ i) = <j> (seg {I} @ i /\ j)
    p' : Id I zero (seg{I} @ i) =
      compId I zero (seg{I} @ i) (seg{I} @ i)
        p
        (refl I (seg{I} @ i))
```

```
Type checking failed: Faces in branch for "seg" don't match:
got
[ (i = 0) -> <!0> hComp I zero [ (!0 = 0) -> <!1> zero, (!0 = 1) -> <!1> zero ], (i = 1) -> <!0> hComp I (seg {I} @ !0) [ (!0 = 0) -> <!1> zero, (!0 = 1) -> <!1> one ] ]
but expected
[ (i = 0) -> <!0> zero, (i = 1) -> <!0> seg {I} @ !0 ]
```

**Comment by coquand** [comment]
I should look more at the example, but in general
we cannot expect that a path p composing with refl  is
the same as p. (We cannot ensure this for composition in the universe.)
Given this, I am not sure if we should expect fromUnitK’
to be well-typed?

**Comment by abooij** [comment]
Okay, after some more discussion and thinking, I am now convinced this is not a bug (or at least none to do specifically with HITs, but just a property of how identity paths in cubicaltt behave in general). Feel free to close this "bug".
