### ISSUE TITLE
Evaluation seems to be too strict

### ISSUE THREAD

**Issue by nad** [mortberg/cubicaltt#4]
The code below is rejected:

```
module test where

import prelude
import nat

foo : nat = undefined

fooIsFoo : Id nat foo foo = refl nat foo
```

Error message:

```
eval: undefined at test_L6_C13
```

Why are you evaluating `foo`?

**Comment by simhu** [comment]
Nils Anders Danielsson notifications@github.com writes:

> The code below is rejected:
> 
> ```
> module test where
> 
> import prelude
> import nat
> 
> foo : nat = undefined
> 
> fooIsFoo : Id nat foo foo = refl nat foo
> ```
> 
> Error message:
> 
> ```
> eval: undefined at test_L6_C13
> ```
> 
> Why are you evaluating `foo`?

Thanks for reporting.  How type-checking is done currently, terms are
checked against values.  So after the type `Id nat foo foo` is checked,
its value is added to the type-checking context; here `foo` gets
evaluated.  A quick fix for this particular problem is to evaluate
undefined into a closure. (pushed)

-- Simon
