### ISSUE TITLE
Add Identity types

### ISSUE THREAD

**Issue by mortberg** [mortberg/cubicaltt#42]
Add identity types as in the paper and prove univalence expressed using Id instead of Path. 

@simhu : Didn't you do this at some point?

**Comment by simhu** [comment]
See the branch equiv; AFAIR, the proof that univalence holds for Id is not complete but it should be really easy the way univalence is stated in the paper.  (I unfortunately lost some local files during my HD crash..)

**Comment by spitters** [comment]
There is also something in the branch defeq.

**Comment by simhu** [comment]
Err, sorry, I meant defeq of course--thanks Bas!

**Comment by mortberg** [comment]
Resolved by https://github.com/mortberg/cubicaltt/pull/49
