### ISSUE TITLE
Print a warning when a name is shadowed

### ISSUE THREAD

**Issue by mortberg** [mortberg/cubicaltt#43]
It is easy to define something with the same name as something already defined and get very confused. If the system would print a warning it would be easier to figure out what is going wrong.

**Comment by jonsterling** [comment]
We just had the exact same thing happen, and got very confused! 🤣  Maybe I'll file a patch for this soon, if I get around to it.

**Comment by mortberg** [comment]
A PR fixing this would be very appreciated. If you need some pointer to where things are in the code drop me an email. I have made a summary of what is in all the Haskell files for a lecture series that I've been giving, see this: https://github.com/mortberg/cubicaltt/blob/master/lectures/lecture1.ctt#L99

**Comment by mortberg** [comment]
I made a patch for this: https://github.com/mortberg/cubicaltt/pull/66

@jonsterling Can you please test it?
