### ISSUE TITLE
Learning Guide

### ISSUE THREAD

**Issue by ronaldpetty** [mortberg/cubicaltt#57]
Hello,

I am totally new to this area.  I would be interested in the following.

- High level explanation on the purpose / utility (again for non-experts)
- Step by step topic guide to have 'hope' of understanding (maybe just list of expected base knowledge concepts.  ex. Compiler theory -> math -> etc. etc.)

Totally not trying to belittle, just really like to try to understand.

Thank you!

**Comment by mortberg** [comment]
I've given a series of lectures on cubicaltt recently, the notes can be found at: https://github.com/mortberg/cubicaltt/tree/master/lectures

These notes assume a lot more than you are asking for, but as this is a very experimental research project under development I don't think we can provide such a detailed list of background topics. If you are interested in formal verification of software and mathematics I suggest you start by looking at mature systems like Coq or Agda. There are a lot of very good books and tutorials on these systems out there, for instance https://softwarefoundations.cis.upenn.edu/current/index.html.

**Comment by ronaldpetty** [comment]
Awesome!
