### ISSUE TITLE
Parser error messages are truncated too much

### ISSUE THREAD

**Issue by necrosovereign** [mortberg/cubicaltt#95]
In the file Main.hs at the lines 93-94 there is an expression
```haskell
    (\e -> do putStrLn ("Exception: " ++ takeWhile (/='\n')
                                 (show (e :: SomeException)))
```
Which, as I understand, is used to catch exception arising from parsing files.

The presence of ``takeWhile (/='\n')`` in the expression causes the parser error message to be truncated to `Exception: Parse failed in "filename"`. I am not sure if this is the intended behaviour

**Comment by mortberg** [comment]
Interesting. Can you post an example of what the errors look like without this truncation?

**Comment by necrosovereign** [comment]
For example, the following code:
```
module m where

T (A : U) : U = A = A
```
causes error message with the following text:
```
Exception: Parse failed in "m.ctt"
"syntax error at line 3 before = A }"
CallStack (from HasCallStack):
  error, called at Main.hs:188:16 in main:Main
```

**Comment by mortberg** [comment]
Ah right, so with the truncation you don't get the line number? That's what I was suspecting... 

I suspect that we wanted to remove the `CallStack` part but ended up removing too much. How about using `lines` and then `takeWhile (/= "CallStack (from HasCallStack):")` ?

**Comment by necrosovereign** [comment]
I really don't know what is the best solution in this case. Removing the truncation completely works for me

**Comment by mortberg** [comment]
I finally found some free time and pushed: https://github.com/mortberg/cubicaltt/commit/452d973fae544861090fbdea51f4f5da653fb394

This should solve this issue so I'm closing.
